### ISSUE TITLE
Breaks when browserslist includes unreleased Safari versions

### ISSUE THREAD

**Issue by sgomes** [browserslist/browserslist-useragent#38]
On a browserslist that includes `unreleased Safari versions`, the library seems to break when accessed with any Safari version (not just Safari TP), presumably because it's being compared against the browserslist versions.

```
TypeError: Invalid Version: TP.0.0
    at new SemVer (/devpath/wp-calypso/node_modules/semver/semver.js:312:11)
    at compare (/devpath/wp-calypso/node_modules/semver/semver.js:585:39)
    at Function.gte (/devpath/wp-calypso/node_modules/semver/semver.js:634:10)
    at compareBrowserSemvers (/devpath/wp-calypso/node_modules/browserslist-useragent/lib/index.js:182:19)
    at /devpath/wp-calypso/node_modules/browserslist-useragent/lib/index.js:208:93
    at Array.some (<anonymous>)
    at matchesUA (/devpath/wp-calypso/node_modules/browserslist-useragent/lib/index.js:207:25)
```

The issue appears to be the non-numeric nature of Safari TP's version "numbering", possibly when combined with the following `browserslist-useragent` flags: `ignorePatch: true`, `ignoreMinor: true`, `allowHigherVersions: true`.

**Comment by sheerun** [comment]
yup, the same issue

**Comment by florisvink** [comment]
It's a bug form the underlying `browserlist` module. When you have `unreleased versions` in your browserlist query in lists `safari TP` and TP cannot be compared by Semver

**Comment by nathggns** [comment]
same issue!
